# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculatorwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(780, 600)
        MainWindow.setMinimumSize(QtCore.QSize(700, 500))
        MainWindow.setMaximumSize(QtCore.QSize(800, 695))
        MainWindow.setBaseSize(QtCore.QSize(760, 695))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/toolImage/gpa_calculator.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QMainWindow{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"QMenuBar{\n"
"background-color: rgb(129, 157, 200);\n"
"color:white;\n"
"}\n"
"QTableWidget{\n"
"border-radius:10px;\n"
"border:1px solid rgb(129,157,200);\n"
"}\n"
"QSpinBox{\n"
"border-radius:5px;\n"
"}\n"
"QPushButton{\n"
"background-color: rgb(129, 157, 200);\n"
"padding:15px;\n"
"border-radius:5px;\n"
"font-size:14px;\n"
"font-weight:bold;\n"
"font-family:\"Arial Rounded MTBold\";\n"
"}\n"
"#calculategpabutton{\n"
"font-size:18px;\n"
"}\n"
"#calculategpabutton:hover{\n"
"background-color: rgb(111, 105, 200);\n"
"color:white;\n"
"}\n"
"QLabel{\n"
"font: 20pt \"Arial Rounded MT Bold\";\n"
"    color: rgb(111, 105, 200);\n"
"}\n"
"#no_of_courses{\n"
"font: 14pt \"Arial\";\n"
"}\n"
"#no_of_coursesspinbox{\n"
"font-size:16px;\n"
"color:rgb(111, 105, 200);\n"
"border:1px solid  rgb(129, 157, 200);\n"
"}\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("color: rgb(68, 99, 200);")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(16, 16))
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.gpa_tab = QtWidgets.QWidget()
        self.gpa_tab.setObjectName("gpa_tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gpa_tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gpalabel = QtWidgets.QLabel(self.gpa_tab)
        self.gpalabel.setAutoFillBackground(False)
        self.gpalabel.setAlignment(QtCore.Qt.AlignCenter)
        self.gpalabel.setObjectName("gpalabel")
        self.verticalLayout.addWidget(self.gpalabel)
        self.no_of_courses = QtWidgets.QLabel(self.gpa_tab)
        self.no_of_courses.setAlignment(QtCore.Qt.AlignCenter)
        self.no_of_courses.setObjectName("no_of_courses")
        self.verticalLayout.addWidget(self.no_of_courses)
        self.no_of_coursesspinbox = QtWidgets.QSpinBox(self.gpa_tab)
        self.no_of_coursesspinbox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.no_of_coursesspinbox.setFrame(False)
        self.no_of_coursesspinbox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.no_of_coursesspinbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.no_of_coursesspinbox.setMinimum(1)
        self.no_of_coursesspinbox.setMaximum(15)
        self.no_of_coursesspinbox.setObjectName("no_of_coursesspinbox")
        self.verticalLayout.addWidget(self.no_of_coursesspinbox)
        self.gpatable = QtWidgets.QTableWidget(self.gpa_tab)
        self.gpatable.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.gpatable.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.gpatable.setAutoScrollMargin(16)
        self.gpatable.setAlternatingRowColors(True)
        self.gpatable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.gpatable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.gpatable.setGridStyle(QtCore.Qt.DotLine)
        self.gpatable.setRowCount(20)
        self.gpatable.setObjectName("gpatable")
        self.gpatable.setColumnCount(3)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(100, 111, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.gpatable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(100, 101, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.gpatable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        brush = QtGui.QBrush(QtGui.QColor(100, 101, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.gpatable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(100, 101, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.gpatable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(100, 101, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.gpatable.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(100, 101, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.gpatable.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(100, 101, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.gpatable.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(100, 101, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.gpatable.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(100, 101, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.gpatable.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(100, 101, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.gpatable.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(100, 101, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.gpatable.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(100, 101, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.gpatable.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(100, 101, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.gpatable.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(100, 101, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.gpatable.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(100, 101, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.gpatable.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(101, 111, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.gpatable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(101, 111, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.gpatable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(101, 101, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.gpatable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 101, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.gpatable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(100, 101, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.gpatable.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(100, 101, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.gpatable.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(100, 101, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.gpatable.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(100, 101, 200))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.gpatable.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(100, 101, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.gpatable.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(100, 101, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.gpatable.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(100, 101, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.gpatable.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(100, 101, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.gpatable.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(100, 101, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.gpatable.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(100, 101, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.gpatable.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(100, 101, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.gpatable.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(100, 101, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.gpatable.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(100, 101, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.gpatable.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(100, 101, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.gpatable.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(100, 101, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.gpatable.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(100, 101, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.gpatable.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(100, 101, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.gpatable.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(100, 101, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.gpatable.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(100, 101, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.gpatable.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(100, 101, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.gpatable.setItem(6, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(100, 101, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.gpatable.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(100, 101, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.gpatable.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(100, 101, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.gpatable.setItem(7, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(100, 101, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.gpatable.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(100, 101, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.gpatable.setItem(8, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(100, 101, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.gpatable.setItem(8, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(100, 101, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.gpatable.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(100, 101, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.gpatable.setItem(9, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(100, 101, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.gpatable.setItem(9, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(100, 101, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.gpatable.setItem(10, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(100, 101, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.gpatable.setItem(10, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(100, 101, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.gpatable.setItem(10, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(100, 101, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.gpatable.setItem(11, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(100, 101, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.gpatable.setItem(11, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(100, 101, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.gpatable.setItem(11, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(100, 101, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.gpatable.setItem(12, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(100, 101, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.gpatable.setItem(12, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(100, 101, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.gpatable.setItem(12, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(100, 101, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.gpatable.setItem(13, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(100, 101, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.gpatable.setItem(13, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(100, 101, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.gpatable.setItem(13, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(100, 101, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.gpatable.setItem(14, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(100, 101, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.gpatable.setItem(14, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(100, 101, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.gpatable.setItem(14, 2, item)
        self.gpatable.horizontalHeader().setDefaultSectionSize(223)
        self.gpatable.horizontalHeader().setMinimumSectionSize(50)
        self.gpatable.verticalHeader().setCascadingSectionResizes(False)
        self.gpatable.verticalHeader().setSortIndicatorShown(False)
        self.gpatable.verticalHeader().setStretchLastSection(False)
        self.verticalLayout.addWidget(self.gpatable)
        self.calculategpabutton = QtWidgets.QPushButton(self.gpa_tab)
        self.calculategpabutton.setStyleSheet("\n"
"color: rgb(255, 255, 255);")
        self.calculategpabutton.setObjectName("calculategpabutton")
        self.verticalLayout.addWidget(self.calculategpabutton)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.gpa_tab, "")
        self.cgpa_tab = QtWidgets.QWidget()
        self.cgpa_tab.setObjectName("cgpa_tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.cgpa_tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.cgpacalculation = QtWidgets.QLabel(self.cgpa_tab)
        self.cgpacalculation.setStyleSheet("QMainWindow{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"QMenuBar{\n"
"background-color: rgb(129, 157, 200);\n"
"color:white;\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: rgb(129, 157, 200);\n"
"padding:15px;\n"
"border-radius:5px;\n"
"font-size:14px;\n"
"font-weight:bold;\n"
"font-family:\"Arial Rounded MTBold\";\n"
"}\n"
"#calc_cgpabutton{\n"
"color:white;\n"
"font-size:18px;\n"
"}\n"
"#calc_cgpabutton:hover{\n"
"background-color: rgb(111, 105, 200);\n"
"color:white;\n"
"}\n"
"#cgpacalculation{\n"
"font: 20pt \"Arial Rounded MT Bold\";\n"
"    color: rgb(111, 105, 200);\n"
"}\n"
"QLabel{\n"
"font: 14pt \"Arial\";\n"
"color: rgb(111, 105, 200);\n"
"}\n"
"QSpinBox{\n"
"border-radius:5px;\n"
"font-size:16px;\n"
"color:rgb(111, 105, 200);\n"
"border:1px solid  rgb(129, 157, 200);\n"
"}\n"
"QTableWidget{\n"
"border:1px solid  rgb(111, 105, 200);\n"
"border-radius:10px;\n"
"}\n"
"")
        self.cgpacalculation.setAlignment(QtCore.Qt.AlignCenter)
        self.cgpacalculation.setObjectName("cgpacalculation")
        self.verticalLayout_2.addWidget(self.cgpacalculation)
        self.label = QtWidgets.QLabel(self.cgpa_tab)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("font: 14pt \"Arial\";")
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.no_of_semesterspin = QtWidgets.QSpinBox(self.cgpa_tab)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.no_of_semesterspin.setFont(font)
        self.no_of_semesterspin.setStyleSheet("#no_of_semesterspin{\n"
"font-size:16px;\n"
"color:rgb(111, 105, 200);\n"
"border:1px solid  rgb(129, 157, 200);\n"
"}\n"
"")
        self.no_of_semesterspin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.no_of_semesterspin.setMinimum(1)
        self.no_of_semesterspin.setMaximum(16)
        self.no_of_semesterspin.setProperty("value", 1)
        self.no_of_semesterspin.setObjectName("no_of_semesterspin")
        self.verticalLayout_2.addWidget(self.no_of_semesterspin)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tableWidget = QtWidgets.QTableWidget(self.cgpa_tab)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.tableWidget.setFont(font)
        self.tableWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tableWidget.setLineWidth(1)
        self.tableWidget.setMidLineWidth(1)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget.setTextElideMode(QtCore.Qt.ElideRight)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setRowCount(8)
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(68, 99, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(68, 99, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(68, 99, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(68, 99, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(68, 99, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(68, 99, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(68, 99, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(68, 99, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(68, 99, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(68, 99, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget.setItem(7, 1, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(315)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(37)
        self.tableWidget.verticalHeader().setDefaultSectionSize(51)
        self.gridLayout_2.addWidget(self.tableWidget, 0, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        self.calc_cgpabutton = QtWidgets.QPushButton(self.cgpa_tab)
        self.calc_cgpabutton.setStyleSheet("#calc_cgpabutton{\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"#calc_cgpabutton:hover{\n"
"background-color: rgb(111, 105, 200);\n"
"color:white;\n"
"}")
        self.calc_cgpabutton.setObjectName("calc_cgpabutton")
        self.verticalLayout_3.addWidget(self.calc_cgpabutton)
        self.tabWidget.addTab(self.cgpa_tab, "")
        self.gridLayout_4.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 795, 21))
        self.menubar.setObjectName("menubar")
        self.menuAction = QtWidgets.QMenu(self.menubar)
        self.menuAction.setObjectName("menuAction")
        self.menuAbout_Us = QtWidgets.QMenu(self.menubar)
        self.menuAbout_Us.setObjectName("menuAbout_Us")
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setMovable(False)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/toolImage/new_file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew.setIcon(icon1)
        self.actionNew.setObjectName("actionNew")
        self.actionReload = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/toolImage/refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionReload.setIcon(icon2)
        self.actionReload.setObjectName("actionReload")
        self.actionDelete = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/toolImage/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDelete.setIcon(icon3)
        self.actionDelete.setObjectName("actionDelete")
        self.actionContact_Information = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/toolImage/contact_info.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionContact_Information.setIcon(icon4)
        self.actionContact_Information.setObjectName("actionContact_Information")
        self.menuAction.addAction(self.actionNew)
        self.menuAction.addAction(self.actionReload)
        self.menuAction.addAction(self.actionDelete)
        self.menuAbout_Us.addAction(self.actionContact_Information)
        self.menubar.addAction(self.menuAction.menuAction())
        self.menubar.addAction(self.menuAbout_Us.menuAction())
        self.toolBar.addAction(self.actionNew)
        self.toolBar.addAction(self.actionReload)
        self.toolBar.addAction(self.actionDelete)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionContact_Information)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.gpalabel.setText(_translate("MainWindow", "GPA CALCULATION"))
        self.no_of_courses.setText(_translate("MainWindow", "NUMBER OF COURSES "))
        item = self.gpatable.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.gpatable.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.gpatable.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.gpatable.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.gpatable.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.gpatable.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.gpatable.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "7"))
        item = self.gpatable.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "8"))
        item = self.gpatable.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "9"))
        item = self.gpatable.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "10"))
        item = self.gpatable.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "11"))
        item = self.gpatable.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "12"))
        item = self.gpatable.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "13"))
        item = self.gpatable.verticalHeaderItem(13)
        item.setText(_translate("MainWindow", "14"))
        item = self.gpatable.verticalHeaderItem(14)
        item.setText(_translate("MainWindow", "15"))
        item = self.gpatable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "COURSE CODE"))
        item = self.gpatable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "UNITS"))
        item = self.gpatable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "GRADES"))
        __sortingEnabled = self.gpatable.isSortingEnabled()
        self.gpatable.setSortingEnabled(False)
        self.gpatable.setSortingEnabled(__sortingEnabled)
        self.calculategpabutton.setText(_translate("MainWindow", "CALCULATE GPA"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.gpa_tab), _translate("MainWindow", "GPA"))
        self.cgpacalculation.setText(_translate("MainWindow", "CGPA CALCULATION"))
        self.label.setText(_translate("MainWindow", "NUMBER OF SEMESTERS"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "100 Level"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "200 Level"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "300 Level"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "400 Level"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "500 Level"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "600 Level"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "700 Level"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "800 Level"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "1ST SEMESTER"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "2ND SEMESTER"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.calc_cgpabutton.setText(_translate("MainWindow", "CALCULATE CGPA"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.cgpa_tab), _translate("MainWindow", "CGPA"))
        self.menuAction.setTitle(_translate("MainWindow", "File"))
        self.menuAbout_Us.setTitle(_translate("MainWindow", "About Us"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionReload.setText(_translate("MainWindow", "Reload"))
        self.actionReload.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.actionDelete.setText(_translate("MainWindow", "Delete"))
        self.actionDelete.setShortcut(_translate("MainWindow", "Ctrl+Del"))
        self.actionContact_Information.setText(_translate("MainWindow", "Contact Information"))

import actionImages

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

